version: '3.8'
services:
  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - .env
      - MYSQL_USER=prisma
      - MYSQL_PASSWORD=topsecret
      - MYSQL_DATABASE=hrm
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local
