export const NAME_MODELS_AUTOGENERATED = 'models_autogenerated.json'
export const REGISTER_QUEUE_WORKSHIFT_EVENTS = 'workshift-events'
export const QUEUE_CREATING_WORKSHIFT_EVENTS = 'creating-workshift-events'

export function isArrayEmpty(arr: any): boolean {
  if (Array.isArray(arr) && arr.length > 0) {
    return false
  }
  return true
}

export function isObjEmpty(obj: any): boolean {
  if (!obj || Array.isArray(obj)) return true
  for (const prop in obj) {
    if (obj.hasOwnProperty(prop)) {
      return false
    }
  }
  return true
}

export function createCurrentEventIntervalBoundary() {
  const currentDateStart = new Date()
  const currentDateEnd = new Date()
  currentDateStart.setHours(currentDateStart.getHours() - 24)
  // TODO : hoangnam
  /** tạm thời để như thế này */
  currentDateEnd.setHours(23)
  return [currentDateStart, currentDateEnd]
}

/**
 * This function will create a date and every value of it in database is actaully a UTC value
 * - in some specific cases, you can use date.getUTCHours() to get the
 * exactly hours you've saw in database (not recommended)
 * - in most cases, if you want to take the right answer of hours value in your local location,
 *  just use date.getHours() method instead
 */
export function createDate(year: number, month: number, day: number, hours = 0, minute = 0) {
  const monthIndex = month - 1
  const date = new Date(year, monthIndex, day, hours, minute)
  return date
}

export function getDatesFrom(startDate: Date, endDate: Date): Date[] {
  const dates = []
  let currentDate = startDate
  while (currentDate <= endDate) {
    dates.push(currentDate)
    const nextDate = new Date(currentDate)
    nextDate.setDate(nextDate.getDate() + 1)
    currentDate = nextDate
  }
  return dates
}

export function createTodayTimeFrom(hours: number, mins: number) {
  const tmpDate = new Date()
  const year = tmpDate.getFullYear()
  const month = tmpDate.getMonth()
  const date = tmpDate.getDate()
  /**
   * Làm phẳng thời gian để tránh bị vướng víu vào các khoảng
   * miliseconds hoặc seconds không bằng nhau gây bug khi so sánh thời gian
   */
  return new Date(year, month, date, hours, mins)
}
